OPENAI:
  api_key: "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"

  embade_model : "text-embedding-3-small"


pinecone:
  api_key: "a1d658df-8eb2-460b-9c98-567bb1c94353"
  env: "gcp-starter"

huggingface:
  api_key: "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"